from django.db import models

class Car(models.Model):
    car = models.CharField(max_length=256, blank=True, null=True)
    variant = models.CharField(max_length=256, blank=True, null=True)
    img_url = models.URLField(max_length=256, blank=True, null=True)
    average_mpg = models.IntegerField(blank=True, null=True)
    co2_emissions_combined = models.IntegerField(blank=True, null=True)
    co2_tax_band = models.CharField(max_length=8, blank=True, null=True)
    road_tax_year_1 = models.IntegerField(blank=True, null=True)
    road_tax_annual = models.IntegerField(blank=True, null=True)
    insurance_group = models.CharField(max_length=8, blank=True, null=True)
    warranty_duration = models.IntegerField(blank=True, null=True)
    engine_size = models.IntegerField(blank=True, null=True)
    fuel = models.CharField(max_length=32, blank=True, null=True)
    gearbox = models.CharField(max_length=64, blank=True, null=True)
    top_speed = models.IntegerField(blank=True, null=True)
    tank_range = models.IntegerField(blank=True, null=True)
    nought_to_sixty = models.DecimalField(max_digits=7, decimal_places=2, blank=True, null=True)
    max_power = models.IntegerField(blank=True, null=True)
    max_torque = models.IntegerField(blank=True, null=True)
    body_type = models.CharField(max_length=64, blank=True, null=True)
    length = models.IntegerField(blank=True, null=True)
    width = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    seats = models.IntegerField(blank=True, null=True)
    luggage_capacity_seats_up = models.IntegerField(blank=True, null=True)
    luggage_capacity_seats_down = models.IntegerField(blank=True, null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, blank=True, null=True)
