# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('engine_size', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('num_doors', models.IntegerField(null=True)),
                ('top_speed', models.IntegerField(null=True)),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('mpg', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('co2_emissions', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('insurance_group', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
