# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 17:15
from __future__ import unicode_literals

from django.db import migrations

def load_cars_from_sql():
    from carz.settings import BASE_DIR
    import os
    sql_statements = open(os.path.join(BASE_DIR,'picker/sql/cars.sql'), 'r').read()
    return sql_statements

class Migration(migrations.Migration):

    dependencies = [
        ('picker', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_cars_from_sql()),
    ]

